export const workplaces = [
  "Dežurni Ginekolog",
  "Dežurni Porodničar",
  "Dežurni Mlajši",
  "Dežurni Neonatolog",
  "Sprejemi +URG.por.",
  "UKA",
  "Por. sobe",
  "Septika",
  "HSC",
  "D1",
  "D2",
  "D3",
  "D4",
  "ZORA (15.30-19.30)",
  "ADM 1",
  "ADM 2",
  "UZ gin.",
  "UZ por.",
  "UZ neo.",
  "Neo. IN",
  "Neo. odd.",
  "Neo. amb.",
  "OA",
  "Onko oddelčni",
  "CBD 1",
  "CBD 2",
  "Kolpo. amb.",
  "Porod oddelčni",
  "ATN 1",
  "ATN 2",
  "AA 1",
  "AA 2",
  "Amb za OBMP",
  "HSC reprodukcija",
  "IVF UZ",
  "Punkcije",
  "Reprodukcija oddelčni",
  "Splošna oddelčni",
  "UDK",
  "Konzilij",
  "Psiholog",
  "MF MB",
  "OP",
  "Seminar",
  "Prosti dan",
  "Dopust",
  "SI",
  "BS",
];

export const workplaceMapping = {
  "Dežurni Ginekolog": ["Dežurstva.Ginekolog"],
  "Dežurni Porodničar": ["Dežurstva.Porodničar"],
  "Dežurni Mlajši": ["Dežurstva.Mlajši"],
  "Dežurni Neonatolog": ["Neonatologija.Dežurstvo"],
  "Sprejemi +URG.por.": [
    "Splošna.Sprejemi",
    "Onkologija.Spre",
    "Reprodukcija.Sprej",
  ],
  UKA: [],
  "Por. sobe": ["Porodnišnica.Porodne sobe"],
  Septika: ["Splošna.Septika", "Onkologija.Sep", "Reprodukcija.Septika"],
  HSC: ["Splošna.HSC", "Onkologija.HSC"],
  D1: [
    "Porodnišnica.Disp 1",
    "Splošna.Disp 1",
    "Onkologija.Disp 1",
    "Reprodukcija.D1",
  ],
  D2: [
    "Porodnišnica.Disp 2",
    "Splošna.Disp 2",
    "Onkologija.Disp 2",
    "Reprodukcija.D2",
  ],
  D3: [
    "Porodnišnica.Disp 3",
    "Splošna.Disp 3",
    "Onkologija.Disp 3",
    "Reprodukcija.D3",
  ],
  D4: ["Onkologija.Disp 4"],
  "ZORA (15.30-19.30)": [],
  "ADM 1": ["Splošna.ADM 1"],
  "ADM 2": ["Splošna.ADM 2"],
  "UZ gin.": ["Splošna.UZ gin", "Onkologija.UZ gin", "Reprodukcija.UZ gin"],
  "UZ por.": ["Porodnišnica.UZ"],
  "UZ neo.": ["Neonatologija.Ultrazvok"],
  "Neo. IN": ["Neonatologija.Neo Intenziva"],
  "Neo. odd.": ["Neonatologija.Oddelek"],
  "Neo. amb.": ["Neonatologija.Ambulanta"],
  OA: ["Onkologija.OA"],
  "Onko oddelčni": ["Onkologija.Odd"],
  "CBD 1": ["Onkologija.CBD"],
  "CBD 2": ["Onkologija.CBD 2"],
  "Kolpo. amb.": ["Onkologija.Kolp"],
  "Porod oddelčni": ["Porodnišnica.Oddelek"],
  "ATN 1": ["Porodnišnica.ATN"],
  "ATN 2": ["Porodnišnica.ATN 2"],
  "AA 1": ["Reprodukcija.AA1"],
  "AA 2": ["Reprodukcija.AA 2"],
  "Amb za OBMP": ["Reprodukcija.Amb za OBMP"],
  "HSC reprodukcija": ["Reprodukcija.HSC"],
  "IVF UZ": ["Reprodukcija.IVF UZ"],
  Punkcije: ["Reprodukcija.Punkcije"],
  "Reprodukcija oddelčni": [],
  "Splošna oddelčni": ["Splošna.Odd sp gin"],
  UDK: ["Splošna.UDK"],
  Konzilij: ["Onkologija.Kon"],
  Psiholog: [],
  "MF MB": [
    "Porodnišnica.MF",
    "Splošna.Vaje MF",
    "Onkologija.MF",
    "Reprodukcija.MF",
  ],
  OP: ["Splošna.Op", "Onkologija.OP", "Reprodukcija.OP"],
  Seminar: [],
  "Prosti dan": [
    "Porodnišnica.PD",
    "Splošna.Prosti dan",
    "Onkologija.PD",
    "Reprodukcija.P po Dež",
  ],
  Dopust: [
    "Porodnišnica.Dopust",
    "Neonatologija.Dopust",
    "Splošna.Dopust",
    "Onkologija.Dop",
    "Reprodukcija.RLD",
  ],
  SI: [
    "Porodnišnica.SI",
    "Neonatologija.SI-Službena-Pot",
    "Splošna.SI",
    "Onkologija.SI",
    "Reprodukcija.SI",
  ],
  BS: ["Reprodukcija.BS"],
};
